CREATE TABLE PRODUCT3
(
	ID NUMBER(38,0),
	NAME VARCHAR2(100),
	CONTENT VARCHAR2(100),
	PRICE NUMBER(38,0),
	COMPANY VARCHAR2(100),
	IMAGE VARCHAR2(100)
)

ALTER TABLE PRODUCT3 
DROP COLUMN IMAGE

--1
--2
SELECT * FROM PRODUCT3
ORDER BY PRICE

--3
SELECT NAME, CONTENT, PRICE FROM PRODUCT3
ORDER BY COMPANY DESC

--4
SELECT DISTINCT COMPANY FROM PRODUCT3

--5
SELECT PRICE*5 AS PRICE5 FROM PRODUCT3

--6
SELECT NAME, COMPANY FROM PRODUCT3 WHERE PRICE = 5000

--7
SELECT NAME, PRICE, COMPANY FROM PRODUCT3 WHERE PRICE BETWEEN 3000 AND 6000
-- = SELECT NAME, PRICE, COMPANY FROM PRODUCT3 WHERE PRICE >= 3000 AND PRICE <= 6000

--8
SELECT COMPANY, NAME FROM PRODUCT3 WHERE COMPANY != 'c100'

--9
SELECT NAME, PRICE FROM PRODUCT3 WHERE COMPANY = 'c100' OR COMPANY = 'c200'
-- = SELECT NAME, PRICE FROM PRODUCT3 WHERE COMPANY IN ('c100', 'c200')

--10
SELECT * FROM PRODUCT3 WHERE NAME LIKE '%4'

--11
SELECT * FROM PRODUCT3 WHERE CONTENT LIKE '%food%'

--12
UPDATE PRODUCT3 SET CONTENT = '품절' WHERE PRICE = 5000

--13
UPDATE PRODUCT3 SET IMG = 'o.png', PRICE = 10000 WHERE ID = '100' OR ID = '102'
-- = UPDATE PRODUCT3 SET IMG = 'o.png', PRICE = 10000 WHERE ID IN ('100', '200')

--14
DELETE FROM PRODUCT3 WHERE COMPANY = 'c100'

--15
DELETE FROM PRODUCT3

SELECT * FROM PRODUCT3
